# Generated by Django 2.1.5 on 2020-10-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0004_auto_20201021_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
