# Generated by Django 2.1.5 on 2020-10-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0005_auto_20201021_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
            ],
        ),
    ]
