# Generated by Django 2.1.5 on 2020-10-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0007_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('FA', 'Faculty'), ('AD', 'Advisor'), ('RE', 'Reviewer')], max_length=25),
        ),
    ]
