# Generated by Django 2.1.5 on 2020-10-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0008_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_faculty',
        ),
    ]
