# Generated by Django 2.1.5 on 2020-10-24 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0008_auto_20201023_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(max_length=500, upload_to='artifacts')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FITaccreditation.Course')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FITaccreditation.Outcome')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='satisfiedoutcome',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfiedoutcome',
            name='artifacts',
            field=models.ManyToManyField(blank=True, to='FITaccreditation.Artifact'),
        ),
    ]
