# Generated by Django 2.1.5 on 2020-10-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0010_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
