# Generated by Django 2.1.5 on 2020-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0012_auto_20201026_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('CE', 'Computer Science and Software Engineering')], max_length=2),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='program',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('CE', 'Computer Science and Software Engineering')], max_length=2),
        ),
    ]
