# Generated by Django 2.1.5 on 2021-02-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0014_userprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='outcome',
        ),
        migrations.AddField(
            model_name='artifact',
            name='outcome',
            field=models.ManyToManyField(blank=True, to='FITaccreditation.Outcome'),
        ),
    ]
