# Generated by Django 2.1.5 on 2021-02-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0015_auto_20210201_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='outcome',
            field=models.ManyToManyField(blank=True, null=True, to='FITaccreditation.Outcome'),
        ),
    ]
