# Generated by Django 2.1.5 on 2021-04-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0016_auto_20210205_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('set_type', models.CharField(choices=[('AS', 'Assignment'), ('EX', 'Exam'), ('OT', 'Other')], max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('artifacts', models.ManyToManyField(blank=True, null=True, to='FITaccreditation.Artifact')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FITaccreditation.Course')),
                ('outcome', models.ManyToManyField(blank=True, null=True, to='FITaccreditation.Outcome')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_faculty',
        ),
    ]
