# Generated by Django 2.1.5 on 2021-04-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0017_auto_20210409_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artifactset',
            unique_together={('name', 'course')},
        ),
    ]
