# Generated by Django 2.1.5 on 2021-04-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FITaccreditation', '0018_auto_20210409_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifactset',
            old_name='outcome',
            new_name='outcomes',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='satisfiedoutcome',
            name='artifacts',
        ),
        migrations.AddField(
            model_name='satisfiedoutcome',
            name='artifact_sets',
            field=models.ManyToManyField(blank=True, to='FITaccreditation.ArtifactSet'),
        ),
    ]
